version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/MedievalIo.Web/ClientApp"
    schedule:
      interval: "daily"
    target-branch: "test"
    labels:
      - "test dependencies"
  - package-ecosystem: "npm"
    directory: "/MedievalIo.Web/ClientApp"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "master dependencies"