version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/MedievalIo.Web/ClientApp"
    schedule:
      interval: "daily"
    target-branch: "test"
    allow:
      - dependency-type: "production"
    labels:
  - package-ecosystem: "npm"

      - "test dependencies"
    directory: "/event-messages-editor"
    schedule:
      interval: "daily"
    target-branch: "master"
    allow:
      - dependency-type: "production"
    labels:
      - "master dependencies"